language: elixir
elixir:
  - 1.6.6
  - 1.7.3
  - 1.8.2
  - 1.9.4
otp_release:
  - 20.3
  - 21.1
  - 22.1
matrix:
  exclude:
  - elixir: 1.6.6
    otp_release: 21.1
dist: trusty
sudo: false
services: true

cache:
  directories:
    - _build
    - deps

before_install: true

before_script:
  - mix local.hex --force
  - mix deps.get --only test
  - mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt

script:
 - MIX_ENV=test mix coveralls.travis
 - mix dialyzer --halt-exit-status